# Generated by Django 4.0.5 on 2022-06-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('contact_no', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='patients/photos')),
                ('nic', models.CharField(max_length=20)),
                ('notes', models.TextField()),
            ],
        ),
    ]
