# Generated by Django 4.0.5 on 2022-06-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_consultation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
