# Generated by Django 4.0.5 on 2022-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
